version: '3.8'

services:
  bot:
    build: .
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - WEB_APP_URL=https://auto-lombard.serveo.net
    restart: unless-stopped

  web:
    image: nginx:alpine
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    ports:
      - "8443:443"
      - "8080:80"

  tunnel:
    image: alpine:latest
    command: >
      sh -c "apk add --no-cache openssh &&
             ssh -o StrictHostKeyChecking=no -R auto-lombard:80:web:80 serveo.net"
    depends_on:
      - web