version: '3.8'

services:
  bot:
    build: .
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - WEB_APP_URL=https://purely-picked-koala.ngrok-free.app
    restart: unless-stopped

  web:
    image: nginx:alpine
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    ports:
      - "8443:443"
      - "8080:80"

  tunnel:
    image: ngrok/ngrok:latest
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    command: http --domain=purely-picked-koala.ngrok-free.app web:80
    ports:
      - "4040:4040"
    depends_on:
      - web