version: '3.8'

services:
  bot:
    build: .
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - WEB_APP_URL=http://localhost:8080
    network_mode: "host"
    restart: unless-stopped

  web:
    image: nginx:alpine
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro
    network_mode: "host"
    ports:
      - "8080:80"